### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by yunnex-xw** [nrn/outside#1]
![image](https://cloud.githubusercontent.com/assets/22461433/20784578/1e2ca580-b7d6-11e6-9a5e-e14e535ddde4.png)

**Comment by nrn** [comment]
Hello @xxxxzz. I don't want to be discouraging as I see this is your first issue, but there is no indication that you are a human, or that this issue has anything to do with this library. If you do need help I'd be happy to, just let me know why this issue ended up here, and maybe add an image to your github profile as some indication you aren't a bot.
